# Generated by Django 4.2.4 on 2023-09-04 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['pptx', 'docx', 'xlsx', 'pdf'])])),
                ('date', models.DateTimeField(verbose_name='04-Mon-2023')),
            ],
        ),
    ]
